export const data=[
    {
        question:"HTML stands for -",
        option1:"HighText Machine Language",
        option2:"HyperText Markup Language",
        option3:"HyperText and links Markup Language",
        option4:"None of these",
        ans:2,
    },
    {
        question:"The correct sequence of HTML tags for starting a webpage is -",
        option1:"Head, Title, HTML, body",
        option2:"HTML, Body, Title, Head",
        option3:"HTML, Head, Title, Body",
        option4:"HTML, Head, Body, Title",
        ans:3 , 
    },
    {
    question:"CSS stands for -",
    option1:"Cascade style sheets",
    option2:"Color and style sheets",
    option3:"Cascading style sheets",
    option4:"None of the above",
    ans:3,
},
{
    question:"Which of the following is the correct syntax for referring the external style sheet?",
    option1:"<style src = example.css>",
    option2:"<stylesheet> example.css </stylesheet>",
    option3:"<link rel='stylesheet' type='text/css' href='example.css'>",
    option4:"All of the Above",
    ans:3,
},
{
    question:" Which type of JavaScript language is ___",
    option1:"Object-Oriented",
    option2:"Object-Based",
    option3:"Assembly-language",
    option4:"High-level",
    ans:2,
},
{
    question:"Which one of the following also known as Conditional Expression:",
    option1:"Alternative to if-else",
    option2:"Switch statement",
    option3:"If-then-else statement",
    option4:"immediate if",
    ans:3,
},
{
    question:"Which of the following option leads to the portability and security of Java?",
    option1:"Bytecode is executed by JVM",
    option2:"The applet makes the Java code secure and portable",
    option3:"Use of exception handling",
    option4:"Dynamic binding between objects",
    ans:1,
},
{
    question:" Which of the following is not a Java features?",
    option1:"Dynamic",
    option2:"Architecture Neutral",
    option3:"Use of pointers",
    option4:"Object-oriented",
    ans:3,
},
{
    question:" What is the maximum possible length of an identifier?",
    option1:"16",
    option2:"32",
    option3:"64",
    option4:"None Of These",
    ans:4,
},
{
    question:"Who developed the Python language?",
    option1:"Zim Den",
    option2:"Guido van Rossum",
    option3:"Niene Stom",
    option4:"Wick van Rossum",
    ans:2,
},
]